version: "2"
services:

  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
    restart : on-failure
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8082:80"  
    restart: always
        
    depends_on:
      - mysql-standalone
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  achatproject-container:
    image: khoukha/projet
    container_name: achat-container
    ports:
      - 8088:8088
    restart: unless-stopped
    environment :
      -SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/achatdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      -SPRING_DATASOURCE_USERNAME : root
      -SPRING_DATASOURCE_PASSWORD : root
    depends_on:
      - mysql-standalone
    links:
      - mysql-standalone:mysql-standalone
