# docker-compose.yml
version: '2'
services:
 mysql-standalonee:
  image: mysql:8
  container_name: mysql-standalonee
  restart: unless-stopped
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=achatdb
  - MYSQL_PASSWORD_=root
  - MYSQL_USERNAME=root
  ports:
  - "3307:3306"
  volumes:
  - 'my-db:/var/lib/mysql'
 spring_apppp:
  image: khoukha/achat
  container_name: devopsachatproject
  ports:
  - "8088:8088"
  restart: unless-stopped
  environment:
  - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-standalonee:3306/achatdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
  - SPRING_DATASOURCE_USERNAME=root
  - SPRING_DATASOURCE_PASSWORD=root
  depends_on:
  - mysql-standalonee
  links:
  - mysql-standalonee:mysql-standalonee
volumes:

  my-db:
