# docker-compose.yml
version: '2'
services:
 mysql-standalone:
  image: mysql:8
  container_name: mysql-standalone
  restart: unless-stopped
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=achatdb
  - MYSQL_PASSWORD_=root
  - MYSQL_USERNAME=root
  ports:
  - "3306:3306"
  volumes:
  - 'my-db:/var/lib/mysql'
 spring_app:
  image: khoukha/achat-spring
  container_name: aachatproject
  ports:
  - "8089:8089"
  restart: unless-stopped
  environment:
  - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-standalone:3306/achatdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
  - SPRING_DATASOURCE_USERNAME=root
  - SPRING_DATASOURCE_PASSWORD=root
  depends_on:
  - mysql-standalone
  links:
  - mysql-standalone:mysql-standalone
 sonarqube:
  image: sonarqube:8.9.7-community
  ports:
  - "9000:9000"
  - "9092:9092"
  volumes:
  - 'SonarQube_data:/opt/SonarQube/data'
  - 'SonarQube_extensions:/opt/SonarQube/extensions'
  - 'SonarQube_logs:/opt/SonarQube/logs'
 nexus:
  image: sonatype/nexus3
  ports:
  - "8081:8081"
  volumes:
  - 'nexus-data:/nexus-data'
volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  nexus-data:
  my-db:
